apiVersion: processors.kops.neuadvcloud.xyz/v1
kind: GithubReleasesMonitor
metadata:
  labels:
    app.kubernetes.io/name: cve-operator
    app.kubernetes.io/managed-by: kustomize
  name: githubreleasesmonitor-sample-2
spec:
  monitorFrom: "now"
  repoUrl: "https://github.com/CVEProject/cvelistV5"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: regcred
          containers:
            - name: webapp-cve-processor
              image: rsiriganagari/webapp-cve-processor:latest
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: 500m
                  memory: 1024Mi
                requests:
                  cpu: 300m
                  memory: 512Mi
              env:
                - name: SASL_USERNAME
                  value: user1
                - name: SASL_PASSWORD
                  value: Y8ybVh4mvT
                - name: KAFKA_BROKERS
                  value: "kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092,kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:9092,kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local:9092"
                - name: KAFKA_TOPIC
                  value: cve
 
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: app.kubernetes.io/name
                          operator: In
                          values:
                            - webapp-cve-processor
                    topologyKey: topology.kubernetes.io/zone
